### ISSUE TITLE
Why not using Dagger Android Support?

### ISSUE THREAD

**Issue by Rainer-Lang** [vestrel00/android-dagger-butterknife-mvp#39]
I think the most devs are using the support libs.

**Comment by vestrel00** [comment]
@Rainer-Lang Good question! I'm forward-looking so when I create new projects I usually set the minSdkVersion to 21 (Lollipop). This allows me not to worry about having to use support Fragment and Activities. I could set the minSdkVersion to 19 (KitKat) to cover the majority of the Android devices: https://developer.android.com/about/dashboards/index.html but I'll leave it at Lollipop for the material theme.

There is a small section in the official Dagger Android docs that addresses users of Android support libraries: https://google.github.io/dagger/android.html#support-libraries

I will update my article to mention this. However, I will not use support fragments and activities in this project. I'll leave that as an exercise to people who want to (or need to) use the support lib. It should be pretty straightforward (so it seems). 

Closing as won't fix. Thanks for the great question!

**Comment by Rainer-Lang** [comment]
@vestrel00 Thanks for the answer.

**Comment by vestrel00** [comment]
@Rainer-Lang Added the following to the article. Thanks again for bringing this up!

> Note: For support Fragment and (AppCompat) Activity users, read the official guide. The main key difference is that AndroidSupportInjectionModule and HasSupportFragmentInjector are used instead of AndroidInjectionModule and HasFragmentInjector. Another key difference is that AndroidSupportInjection.inject() is used instead of the usual AndroidInjection.inject() when injecting support Fragments. Take a look at the dagger.android.support package to get started.
This article will not cover the support lib for brevity.

**Comment by vestrel00** [comment]
I've created an issue to showcase how to use the support libs. See #48.
