### ISSUE TITLE
Introduce tests?

### ISSUE THREAD

**Issue by chronvas** [vestrel00/android-dagger-butterknife-mvp#50]
would it be useful to introduce tests in this project?

**Comment by vestrel00** [comment]
@chronvas It may be useful but let's not do it. Tests are essential in any project. However, we should keep this project as focused as possible and not introduce anything that isn't really a part of the guide/blog/article. Perhaps tests should be a part of the guide or at least be mentioned, but testing is another huge topic itself. The guide should be kept as short and focused as possible. 

I'll close this as won't fix for now. Thanks!

**Comment by vestrel00** [comment]
I talked a little bit more about testing in #52
