### ISSUE TITLE
Provide Kotlin translations for the Java code in the master-support branch

### ISSUE THREAD

**Issue by vestrel00** [vestrel00/android-dagger-butterknife-mvp#62]
The Kotlin code mirroring the Java code in the **master-support** branch should be placed in a new branch called **master-support-kotlin**.

**Comment by ysmintor** [comment]
If you introduce Kotlin version, then I think there is a great modification from the original source as the Kotlin feature provided.

**Comment by vestrel00** [comment]
Closed by https://github.com/vestrel00/android-dagger-butterknife-mvp/pull/68
