### ISSUE TITLE
Providing activity context

### ISSUE THREAD

**Issue by ClaudeHangui** [vestrel00/android-dagger-butterknife-mvp#75]
I'm trying to follow-up what you did just did inside your sample. I am having a hard-time building the app because of the Context and abstract Presenter injected inside BaseActivity and BasePresenter respectively.

For the Context, here's the error I have:

`Error:(35, 8) error: [dagger.android.AndroidInjector.inject(T)] android.support.v7.app.AppCompatActivity cannot be provided without an @Inject constructor or from an @Provides-annotated method.
android.support.v7.app.AppCompatActivity is injected at
mypackage.base.BaseActivityModule.activityContext(activity)
android.content.Context is injected at
mypackage.base.BaseFragment.activityContext
`

The BaseActivity and BaseFraggement classes have been left unchanged. I simply extended them to my activities and fragments.

Here's my CoreComponent interface:
`@Singleton
@Component(modules = {ContextModule.class,
        NetworkModule.class, AppHelperModule.class, StorageModule.class,
        SchedulerFacadeImplModule.class, DatabaseModule.class})
public interface CoreComponent extends AndroidInjector<MyApp>
{
    @Component.Builder
    abstract class Builder extends AndroidInjector.Builder<MyApp> {
    }
}
`

and here's my ContextModule class:
`@Module(includes = AndroidInjectionModule.class)
public abstract class ContextModule
{
    @Binds
    abstract Application application(CoreApp coreApp);

    @PerActivity
    @ContributesAndroidInjector(modules = MainViewModule.class)
    abstract MainView provideMainView();
}`

MainView is the name of my activity

**Comment by vestrel00** [comment]
@ClaudeHangui, you need to provide an instance of `AppCompatActivity` in all of your Activity modules.

I'm not sure exactly what your setup is so you can use the below snippet of code (taken from this project) as reference for a working setup.

```java
@Singleton
@Component(modules = AppModule.class)
interface AppComponent extends AndroidInjector<App> {

    @Component.Builder
    abstract class Builder extends AndroidInjector.Builder<App> {
    }
}

@Module(includes = AndroidSupportInjectionModule.class)
abstract class AppModule {

    @Binds
    @Singleton
    abstract Application application(App app);

    @PerActivity
    @ContributesAndroidInjector(modules = MainActivityModule.class)
    abstract MainActivity mainActivityInjector();
    ...
}

@Module(includes = BaseActivityModule.class)
public abstract class MainActivityModule {

    @Binds
    @PerActivity
    abstract AppCompatActivity appCompatActivity(MainActivity mainActivity);
    ...
}

/**
 * Provides base activity dependencies. This must be included in all activity modules, which must
 * provide a concrete implementation of {@link AppCompatActivity}.
 */
@Module
public abstract class BaseActivityModule {

    @Binds
    @PerActivity
    abstract Activity activity(AppCompatActivity appCompatActivity);

    @Binds
    @PerActivity
    abstract Context activityContext(Activity activity);
    ...
}
```

> The above code is taken from the **master-support** branch, which uses the support libs. I used the support branch for the below snippet because the error you provided suggested that you are using the support libs (`AppCompatActivity`).

**Notice** a couple of things in the above snippet;

1. The `AppModule` includes the `AndroidSupportInjectionModule.class`, which is required when using the support libs (`AppCompatActivity`). _Note that you may include the injection module in your `AppComponent`. It's the same thing._

2. The `MainActivityModule` includes `BaseActivityModule.class` as all activity modules should include as stated in the class javadoc of `BaseActivityModule`.

3. The `MainActivityModule` provides (`binds`) an instance of `AppCompatActivity` as required per the contract specified by the `BaseActivityModule`. 

In the above snippet, your `@PerActivity`, `@PerFragment`, and `@PerChildFragment` scoped dependencies will have access to the following types of contexts;

- `Application`
- `AppCompatActivity`
- `Activity`
- `Context` (from the `Activity`, not the `Application`)

**Comment by ClaudeHangui** [comment]
Indeed I did forgot this line inside the BaseActivityModule class :

` @Binds
    @PerActivity
    abstract Activity activity(AppCompatActivity appCompatActivity);`

The issue is solved with the Context injected.
But what about the presenter ?

Let me show you my base classes, maybe you'll see something I can't :)

BaseInteractor (or BaseModel):
`public interface IBaseInteractor {

}`

BaseView :
`public interface IBaseView
{
    void close();
    boolean isDeviceConnected();
    void saveState();
    void retrieveState();
}`

BasePresenter : 
`public interface IBasePresenter<V extends IBaseView, I extends IBaseInteractor>
{
    void onViewAttached(V view, boolean isNewViewInstance);
    void onStart(@Nullable Bundle savedInstanceState);
    V getMvpView();
    I getInteractor();
    void onResume();
    void onPause();
    void onSaveInstanceState(Bundle outState);
    void onEnd();
    void onViewDetach();
}` 

I'm having the problem with the Presenter inside my fragments, so:

BaseViewFragment:

`public abstract class BaseViewFragment <T extends IBasePresenter> extends BaseFragment
        implements IBaseView
{
    @Inject
    protected T presenter;
    private boolean isNewFragment;
    
    @Override
    public void onViewStateRestored(@Nullable Bundle savedInstanceState) {
        super.onViewStateRestored(savedInstanceState);
        presenter.onStart(savedInstanceState);
    }

    @Override
    public void onResume() {
        super.onResume();
        presenter.onResume();
        presenter.onViewAttached(this, isNewFragment);
        isNewFragment = false;
    }

    @Override
    public void onPause() {
        presenter.onPause();
        presenter.onViewDetach();
        super.onPause();
    }

    protected abstract void setUp(View view);

    @Override
    public void onDestroyView() {
        presenter.onEnd();
        super.onDestroyView();
    }
}`

I have this presenter class which extends my BasePresenter class:

`public class RadioMenuPresenter<V extends IRadioMvpView, I extends IRadioInteractor>
    extends BasePresenter<V, I> implements IRadioPresenter<V, I>`

where :

`public abstract class BasePresenter<V extends IBaseView, I extends IBaseInteractor> implements IBasePresenter<V, I>`

I did not want to write too much so I purposely omitted the implementations for the BasePresenter and RadioMenuPresenter.

Last but not the least, my RadioModule class:

`
@Module
public abstract class RadioModule
{
    @Binds @PerFragment
    abstract IRadioInteractor provideRadioInteractor(RadioInteractor radioInteractor);
    @Binds @PerFragment
    abstract IRadioMvpView provideRadioMenuView(RadioMenuView radioMenuView);
    @Binds @PerFragment
    abstract IRadioPresenter<IRadioMvpView, IRadioInteractor>
    provideRadioPresenter(RadioMenuPresenter<IRadioMvpView, IRadioInteractor> radioMenuPresenter);
}
`

RadioMenuView is my fragment
Here's the error as shown on my terminal :

`Error:(36, 8) error: [dagger.android.AndroidInjector.inject(T)] mypackage.RadioMenuPresenter cannot be provided without an @Provides- or @Produces-annotated method.
mypackage.RadioMenuPresenter is injected at
mypackage.base.BaseViewFragment.presenter
mypackage.RadioMenuView is injected at
dagger.android.AndroidInjector.inject(arg0)`

Up till now I'm still stuck with this error, I tried to replicate exactly your sample, but looks like the generic Presenter injected in the BaseViewFragment is not considered to be provided

**Comment by vestrel00** [comment]
@ClaudeHangui, the error is saying that you are not providing an instance of `RadioMenuPresenter` in `RadioMenuView`, which is injected at its super class; `BaseViewFragment { T presenter }`. This is how Dagger interprets your setup based on the error;

```java
RadioMenuView {
    RadioMenuPresenter presenter;
    ...
}

RadioModule {
    @Binds
    @PerFragment
    abstract IRadioPresenter<IRadioMvpView, IRadioInteractor> provideRadioPresenter(RadioMenuPresenter<IRadioMvpView, IRadioInteractor> radioMenuPresenter);
}
```

In the above snippet, the `RadioMenuView` is expecting an object with the exact type of  `RadioMenuPresenter`. However, the `RadioModule` is providing an object of type `IRadioPresenter`.

To fix the issue, you have to ensure that you are injecting the exact type that is being provided in the module. I'm assuming you want to inject the interface `IRadioPresenter` instead of its implementation (`RadioMenuPresenter`) into `RadioMenuView`. In that case, you should triple check everything and make sure that your code compiles to;

```java
RadioMenuView {
    IRadioPresenter presenter;
    ...
}
```

Notice that the `IRadioPresenter` is injected instead of `RadioMenuPresenter`.

**Other things you want to double check***

1. Your `RadioMenuPresenter` should have a constructor annotated with `@Inject` so you can use `@Binds`. Otherwise, you will have to use `@Provides` and return a new instance of the `RadioMenuPresenter` yourself in the `RadioModule`.

2. Your `RadioModule` is included in your fragment module or inside the `@ContributesAndroidInjector`.

**Comment by akingyin1987** [comment]
`@Inject
  public UserListAdapter(@ActivityContext Context context) {
    super(null);
   mInflater = LayoutInflater.from(context);
    System.out.println("null==="+(null == context));
  }```

this context is error 

`E:\androidsamples\Dagger2AndroidDemo\app\src\main\java\com\akingyin\dagger2androiddemo\di\component\AppComponent.java:28: 错误:
 [dagger.android.AndroidInjector.inject(T)] @com.akingyin.dagger2androiddemo.di.qualifier.ActivityContext android.app.Activity
cannot be provided without an @Provides-annotated method.
public interface AppComponent extends AndroidInjector<DaggerApp> {
       ^
      @com.akingyin.dagger2androiddemo.di.qualifier.ActivityContext android.app.Activity is injected at
          com.akingyin.dagger2androiddemo.ui.adapter.UserListAdapter.<init>(context)
      com.akingyin.dagger2androiddemo.ui.adapter.UserListAdapter is injected at
          com.akingyin.dagger2androiddemo.ui.MainActivity.mUserListAdapter
      com.akingyin.dagger2androiddemo.ui.MainActivity is injected at
          dagger.android.AndroidInjector.inject(arg0)
`

**Comment by vestrel00** [comment]
Closing this issue since there are no follow ups.

**Comment by TikTak123** [comment]
Hello!
I have the same architecture.
My problem is that I cannot get the AppCompatActivity in the BaseActivityModule.
Could you help me?
My question in Stackoverflow
https://stackoverflow.com/questions/53370219/how-do-i-pass-appcompatactivity-to-module
